quarkus:
  http:
    port: 38080
  grpc:
    server:
      port: 49000
  log:
    level: DEBUG
    console:
      enable: true
    category:
      "com.rokkon":
        level: DEBUG
      "io.grpc":
        level: INFO
        
# Engine dev mode settings
consul:
  host: localhost
  port: 8500