version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.21.1
    container_name: rokkon-consul
    command: "consul agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 -data-dir=/consul/data"
    ports:
      - "8500:8500"  # HTTP API & UI
      - "8600:8600"  # DNS
    networks:
      - rokkon-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  engine:
    image: rokkon/engine:latest
    container_name: rokkon-engine
    depends_on:
      consul:
        condition: service_healthy
    environment:
      # Quarkus Configuration
      QUARKUS_CONSUL_CONFIG_AGENT_HOST_PORT: "consul:8500"
      QUARKUS_VERTX_CONSUL_CLIENT_HOST: "consul"
      QUARKUS_VERTX_CONSUL_CLIENT_PORT: 8500
      
      # Rokkon Configuration
      ROKKON_ENGINE_NAME: "rokkon-engine"
      ROKKON_ENGINE_VERSION: "1.0.0-SNAPSHOT"
      
      # Java options for container
      JAVA_OPTS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
    ports:
      - "8080:8080"  # HTTP API & Dashboard
      - "8081:8081"  # gRPC port
    networks:
      - rokkon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  test-module:
    image: rokkon/test-module:latest
    container_name: rokkon-test-module
    depends_on:
      engine:
        condition: service_healthy
    environment:
      # Module configuration
      MODULE_HOST: "0.0.0.0"
      MODULE_PORT: 9090
      
      # Engine connection for registration
      ENGINE_HOST: "engine"
      ENGINE_PORT: 8081
      
      # Consul connection (optional)
      CONSUL_HOST: "consul"
      CONSUL_PORT: 8500
      
      # Registration settings
      HEALTH_CHECK: "true"
      MAX_RETRIES: 5
      STARTUP_TIMEOUT: 60
      CHECK_INTERVAL: 5
      
      # Java options
      JAVA_OPTS: "-Dquarkus.http.host=0.0.0.0"
    ports:
      - "9090:9090"  # gRPC port
    networks:
      - rokkon-network

networks:
  rokkon-network:
    driver: bridge
    name: rokkon-network