version: '3.8'

services:
  # Consul service for service discovery and configuration
  consul:
    image: hashicorp/consul:1.19.2
    container_name: rokkon-consul
    ports:
      - "8500:8500"       # Consul UI and HTTP API
      - "8600:8600/udp"   # Consul DNS
    command: agent -dev -ui -client=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - rokkon-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Rokkon Engine - must be running for module registration
  rokkon-engine:
    image: rokkon/engine:latest
    container_name: rokkon-engine
    ports:
      - "8081:8081"   # Engine HTTP port
      - "9081:9081"   # Engine gRPC port
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - QUARKUS_HTTP_PORT=8081
      - QUARKUS_GRPC_SERVER_PORT=9081
      - QUARKUS_CONSUL_CONFIG_AGENT_HOST=consul
      - QUARKUS_CONSUL_CONFIG_AGENT_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - rokkon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Test Module with auto-registration
  test-module:
    image: rokkon/test-module:latest
    container_name: rokkon-test-module
    ports:
      - "49095:49095"  # Module gRPC port (from application.yml)
      - "39095:39095"  # Module HTTP port (from application.yml)
    environment:
      # Module configuration
      - MODULE_HOST=test-module    # Hostname within container network
      - MODULE_PORT=49095          # gRPC port from application.yml
      # Engine connection for registration
      - ENGINE_HOST=rokkon-engine
      - ENGINE_PORT=9081           # Engine's gRPC port
      # Consul configuration (optional)
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      # Module application configuration
      - QUARKUS_HTTP_PORT=39095
      - QUARKUS_GRPC_SERVER_PORT=49095
      - QUARKUS_CONSUL_CONFIG_AGENT_HOST=consul
      - QUARKUS_CONSUL_CONFIG_AGENT_PORT=8500
      # Health check configuration
      - HEALTH_CHECK=true
      - MAX_RETRIES=5
      - STARTUP_TIMEOUT=120
    depends_on:
      rokkon-engine:
        condition: service_healthy
    networks:
      - rokkon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:39095/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  rokkon-network:
    name: rokkon-network
    driver: bridge