version: '3.8'

services:
  # Consul service for service discovery and configuration
  consul:
    image: hashicorp/consul:1.19.2
    container_name: rokkon-consul
    ports:
      - "8500:8500"       # Consul UI and HTTP API
      - "8600:8600/udp"   # Consul DNS
    command: agent -dev -ui -client=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - rokkon-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Rokkon Engine - must be running for module registration
  rokkon-engine:
    image: rokkon/engine:latest
    container_name: rokkon-engine
    ports:
      - "8081:8081"   # Engine HTTP port
      - "9081:9081"   # Engine gRPC port
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - QUARKUS_HTTP_PORT=8081
      - QUARKUS_GRPC_SERVER_PORT=9081
      - QUARKUS_CONSUL_CONFIG_AGENT_HOST=consul
      - QUARKUS_CONSUL_CONFIG_AGENT_PORT=8500
      - QUARKUS_CONSUL_AGENT_HOST=rokkon-engine # Force engine to register with its service name
      - ENGINE_HOST=rokkon-engine # Explicitly set engine's advertised host
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - rokkon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  

networks:
  rokkon-network:
    name: rokkon-network
    driver: bridge