quarkus:
  application:
    name: protobuf-stubs
  generate-code:
    grpc:
      scan-for-proto: com.rokkon.pipeline:protobuf,com.google.api.grpc:proto-google-common-protos
  grpc:
    codegen:
      type: both  # Generate both blocking and Mutiny stubs