quarkus:
  application:
    name: rokkon-engine-test
  http:
    port: 0  # Use random port for tests
  grpc:
    server:
      port: 0  # Use random port for tests
  log:
    level: INFO
    category:
      "com.rokkon":
        level: DEBUG