package com.krickert.yappy.wikicrawler.controller;

import io.micronaut.core.annotation.Introspected;

import java.util.List;

// Simple response DTO
@Introspected
@io.swagger.v3.oas.annotations.media.Schema(description = "Response from the crawl initiation request.")
public class CrawlResponse {
    @io.swagger.v3.oas.annotations.media.Schema(description = "Indicates if the overall crawl initiation and processing was accepted or started successfully.")
    public boolean success;
    @io.swagger.v3.oas.annotations.media.Schema(description = "A message detailing the outcome.")
    public String message;
    @io.swagger.v3.oas.annotations.media.Schema(description = "Number of documents successfully ingested into the Yappy engine.")
    public long documentsIngested;
    @io.swagger.v3.oas.annotations.media.Schema(description = "List of stream IDs generated by the Yappy engine for ingested documents.")
    public List<String> streamIds;

    public CrawlResponse(boolean success, String message, long documentsIngested, List<String> streamIds) {
        this.success = success;
        this.message = message;
        this.documentsIngested = documentsIngested;
        this.streamIds = streamIds;
    }
}
