# src/main/resources/application.yml for rokkon-commons
# This configuration is used by the Quarkus build process when building this library.
# It ensures that the protobuf Java classes are generated for this library's compilation classpath,
# so that its own Java code can reference gRPC stubs and message types.
# These generated classes are NOT typically packaged into the final rokkon-commons.jar.
quarkus:
  generate-code:
    grpc:
      # Scans the 'rokkon-protobuf' dependency for .proto files to generate Java classes from.
      # This is crucial for rokkon-commons to compile its own code that uses protobuf types.
      scan-for-proto: com.rokkon.pipeline:rokkon-protobuf,com.google.api.grpc:proto-google-common-protos
  grpc:
    codegen:
      # Specifies that Mutiny-style gRPC stubs should be generated for compilation.
      # This should align with how rokkon-commons's code uses gRPC.
      type: mutiny