# Test profile for integration testing
quarkus:
  # HTTP configuration
  http:
    port: ${QUARKUS_HTTP_PORT:38082}
    host: 0.0.0.0
  
  # gRPC configuration  
  grpc:
    server:
      port: ${QUARKUS_GRPC_SERVER_PORT:48082}
      host: 0.0.0.0
  
  # Consul config - enabled for test
  consul-config:
    enabled: true
    agent:
      host-port: ${QUARKUS_CONSUL_HOST:localhost}:${QUARKUS_CONSUL_PORT:8500}
    properties-value-keys: 
      - config/application
      - config/test
    format: properties
    fail-on-missing-key: false  # Don't fail if profile config missing

# Rokkon configuration
rokkon:
  cluster:
    name: ${CLUSTER_NAME:test-cluster}
  engine:
    name: ${ROKKON_ENGINE_NAME:test-engine}
    grpc-port: ${QUARKUS_GRPC_SERVER_PORT:48082}
    rest-port: ${QUARKUS_HTTP_PORT:38082}
    debug: true