receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Export to LGTM stack (Grafana DevServices)
  otlp/lgtm:
    endpoint: ${LGTM_ENDPOINT:http://host.docker.internal:4317}
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  
  # Log telemetry for debugging
  logging:
    loglevel: debug

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Add resource attributes
  resource:
    attributes:
      - key: deployment.environment
        value: dev
        action: upsert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/lgtm, logging]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/lgtm, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/lgtm, logging]

  telemetry:
    logs:
      level: debug