quarkus:
  application:
    name: test-module
  grpc:
    server:
      port: 49093
      host: 0.0.0.0
      enable-reflection-service: true
  log:
    level: INFO
    category:
      "com.rokkon":
        level: DEBUG
  container-image:
    build: false
    push: false
    registry: "registry.rokkon.com:8443"
    image: "rokkon/test-module:${quarkus.application.version}"
    dockerfile-jvm-path: src/main/docker/Dockerfile.jvm
    group: rokkon

# Module specific configuration
test:
  processor:
    name: test-processor
    delay:
      ms: 0

# Test profile configuration
"%test":
  quarkus:
    grpc:
      server:
        port: 0  # Use random port for tests