quarkus:
  application:
    name: test-module
  generate-code:
    grpc:
      scan-for-proto: com.rokkon.pipeline:protobuf,com.google.api.grpc:proto-google-common-protos
  http:
    port: 39100  # Standard internal module port
    test-port: 0  # Random port for tests
  grpc:
    server:
      use-separate-server: false  # Use unified server
      host: 0.0.0.0
      enable-reflection-service: true
      max-inbound-message-size: 1073741824  # 1GB
      health:
        enabled: true
    clients:
      testService:
        max-inbound-message-size: 1073741824  # 1GB
      TestHarness:
        host: localhost
        port: ${quarkus.http.port}  # Use HTTP port for unified server
  log:
    level: INFO
    category:
      "com.rokkon":
        level: DEBUG
  container-image:
    build: false  # Disable by default, enable via profile
    push: false
    name: test-module
    tag: 1.0.0-SNAPSHOT
    group: rokkon
    # Use docker builder
    builder: docker
    # Additional files to include
    docker:
      dockerfile-jvm-path: src/main/docker/Dockerfile.jvm
      # Build context includes the files we need
      additional-build-args:
        - "--progress=plain"

# Module specific configuration
test:
  processor:
    name: test
    delay:
      ms: 0

# OpenTelemetry configuration
otel:
  enabled: true
  traces:
    enabled: true
  metrics:
    enabled: true
  logs:
    enabled: true
  exporter:
    otlp:
      # In production, this will be set via environment variable to the sidecar collector
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:grpc}
  resource:
    attributes:
      service.name: test-module
      service.namespace: pipeline
      deployment.environment: ${quarkus.profile:prod}

# Micrometer metrics configuration
micrometer:
  enabled: true
  export:
    prometheus:
      enabled: true
  binder:
    jvm: true
    system: true
    grpc:
      server: true
      client: true

# Test profile configuration
"%test":
  quarkus:
    grpc:
      server:
        port: 0  # Use random port for tests
        max-inbound-message-size: 1073741824  # 1GB for tests
      clients:
        testService:
          max-inbound-message-size: 1073741824  # 1GB
    # Disable OpenTelemetry in tests
    otel:
      enabled: false
      sdk:
        disabled: true
    # Disable container image building in tests
    container-image:
      build: false

# Build profile - enable container image building
"%build":
  quarkus:
    container-image:
      build: true
